### ISSUE TITLE
My trips page

### ISSUE THREAD

**Issue by zachuri** [Tramona-Inc/tramona#141]
# Task
- [X] UI: clean and match similar to figma
- [X] Show total on the top of each section
- [ ] Display previous and upcoming trips separably
- [ ] Only display two max within the main page and children pages show more
- [ ] Make an efficient query that only gets top for (2 upcoming and 2 previous)

# Figma 
https://www.figma.com/file/nRLneAarQiaMTyNce7pNGf/Final-Pages-Developers?type=design&node-id=2174%3A149&mode=design&t=IO3EK9dtMfyo1xqm-1
