### ISSUE TITLE
Signup: Update Features

### ISSUE THREAD

**Issue by zachuri** [Tramona-Inc/tramona#146]
# Task
- [x] On signup login the user
- [x] On signout redirect user back to home page
- [x] Fix visible input for password (see password not working)
- [x] Create a forgot password page
- [x] Have a way to verify user email
