### ISSUE TITLE
Notes Oct/28 

### ISSUE THREAD

**Issue by ueharaneal** [Tramona-Inc/tramona#630]
[ ] Currently, some forms have the  check-in and checkout times have default values, we need to remove them forcing the user to put the proper check-in and checkout times. 

[ ] Message host button on trips email does not work 

## To-Do Checklist

- [ ] **Update Dispute List Page**
  - Change "In Review" badges to “Needs attention” if a claim is `inReview` and all claim items have been responded to
  - Create a new router function and component for this update

- [x] **Send Emails on Claim Resolution**
  - Send an email to both the host and traveler once claims are resolved
  - Send "Claim Against" email notification

- [ ] **Update User-Side Text**
  - Change text from "View Details" to "Respond to Claim" on the user side

- [ ] **Restrict Admin Claim Creation**
  - Prevent admins from making multiple claims for the same trip

- [ ] **Create Summary Pages**
  - Summary page of payments for both users and hosts
  - Summary page for deposits held

- [ ] **Sort Disputes and Claim History**
  - Ensure disputes and claim history are sorted at `http://localhost:3000/my-trips/billing/security-deposits`

- [ ] **Fix Billing History UI**
  - Update and improve the UI of the billing history page
  
  ---
  - [ ] **Complete TAXES Page
  -Tax page is currently empty 
  - [x] **Fix the price breakdown on the finances page
  -figure how to query the breakdowns.
  
  --
  -[ ]**Hospitable webhook used country code instead of country be sure to change it @ line 388
